name: Build / Push WASM Binaries

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
      - name: Install YokeCD
        run: go install github.com/yokecd/yoke/cmd/yoke@latest
      - name: Build and push WASM binary
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o .wasm/foo/production/app.wasm ./apps/foo/production/main.go
          yoke stow .wasm/foo/production/app.wasm oci://ghcr.io/seanturner026/yokecd-playground:latest
