name: Build / Push WASM Binaries

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
      - name: Install YokeCD
        run: |
          curl -L -o - "https://github.com/yokecd/yoke/releases/download/v0.16.5/yoke_v0.16.5_linux_amd64.gz" | gunzip  > /usr/local/bin/yoke && \
          chmod +x /usr/local/bin/yoke
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push WASM binary
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o .wasm/foo/production/app.wasm ./apps/foo/production/main.go
          yoke stow .wasm/foo/production/app.wasm oci://ghcr.io/seanturner026/yokecd-playground:latest
